# Generated by Django 4.1 on 2022-12-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuisioner_data_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('code', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='kuisioner',
            name='gender',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='kuisioner',
            name='negara',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='kuisioner',
            name='prov',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='kuisioner',
            name='tujuan',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='kuisioner',
            name='vaksin',
            field=models.TextField(),
        ),
    ]
